default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
      command: ["--privileged"]

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""
  SERVICE_PORT_2376_TCP_PORT: 2375

build:
  stage: build
  before_script:
    - docker info
    - printenv
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin 

  script:
    - docker build -f ./FrontEnd/Dockerfile -t $IMAGE_TAG ./FrontEnd
    - docker push $IMAGE_TAG
  
  only:
    - deployment