// a list of possible types of projects 
const projects = [
    'Web Development',
    'Mobile Development',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Cybersecurity',
    'Game Development',
    'UI/UX Design',
    'Product Management',
    'Digital Marketing',
    'Other'
];

// a list of possible Colleges 
const colleges = [  
    'University of California, Los Angeles',
    'University of California, Berkeley',
    'University of Utah', 
    'University of Washington',
    'University of California, Irvine',
    'Brigham Young University',
    'Stanford University',
    'Yale University',
    'Harvard University',
];

// a list of possible skills 
const skills = [    
    'React',
    'JavaScript',
    'Python',
    'Java',
    'C++',
    'C#',
    'SQL',
    'HTML',
    'CSS',
    'Node.js',
    'Express.js',
    'MongoDB',
    'PostgreSQL',
    'Django',
    'Flask',
    'Spring',
    'Android',
    'iOS',
    'Swift',
    'Kotlin',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'Numpy',
    'Matplotlib',
    'Seaborn',
    'Plotly',
    'Tableau',
    'PowerBI',
    'Excel',
    'Word',
    'PowerPoint',
    'Outlook',
    'Google Docs',
    'Google Sheets',
    'Google Slides',
    'Figma',
    'Adobe XD',
    'Adobe Photoshop',
    'Adobe Illustrator',
    'Adobe InDesign',
    'Adobe Premiere Pro',
    'Adobe After Effects',
    'Adobe Lightroom',
    'Adobe Audition',
    'Blender',
    'Unity',
    'Unreal Engine',
    'CryEngine',
    'Godot',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'Premiere Pro',
    'After Effects',
    'Lightroom',
    'Audition',
    'Blender',
    'Unity',
    'Unreal Engine',
    'CryEngine',
    'Godot',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Instagram Ads',
    'LinkedIn Ads',
    'Twitter Ads',
    'Pinterest Ads',
    'Snapchat Ads',
    'TikTok Ads',
    'SEO',
    'SEM',
    'SMM',
    'Email Marketing',
    'Content Marketing',
    'Affiliate Marketing',
    'Influencer Marketing',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Instagram Ads',
    'LinkedIn Ads',
    'Twitter Ads',
    'Pinterest Ads',
    'Snapchat Ads',
    'TikTok Ads',
    'SEO',
    'SEM',
    'SMM',
    'Email Marketing',
    'Content Marketing',
    'Affiliate Marketing',
    'Influencer Marketing',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
];

const distances = [0, 10, 25, 50, 100];

export { projects, colleges, skills, distances };